### ISSUE TITLE
KeyError: 'dataset'

### ISSUE THREAD

**Issue by zslittlehelper** [1aienthusiast/audiocraft-infinity-webui#11]
Tried to get this running on windows on a venv with py3.9, only got the below error.
Tried once more in WSL2 with py3.9 in a conda environment, same error.

Any suggestions on what might be going wrong?

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/gradio/routes.py", line 289, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/home/dude/miniconda3/envs/infinityaudio/lib/python3.9/site-packages/gradio/blocks.py", line 517, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'`

**Comment by 1aienthusiast** [comment]
have you done `pip install -r requirements.txt`, what is your gradio version

**Comment by zslittlehelper** [comment]
> have you done `pip install -r requirements.txt`, what is your gradio version

Yes, tried it once more as well: "Requirement already satisfied: gradio==3.34.0"

**Comment by gloic** [comment]
same issue for me, i found a similar issue on A1111 https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855#issuecomment-1641254504
`pip install gradio_client==0.2.7` worked for me too

**Comment by mykeehu** [comment]
Need fix it in requirements.txt, which needs to be checked anyway, because it's not installed correctly.
